In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("matches.csv")
deliveries = pd.read_csv("deliveries.csv")

In [3]:
matches.head(5)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [6]:
deliveries.head(5)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [7]:
matches.info()
deliveries.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1044 non-null   str
 3   date             1095 non-null   str
 4   match_type       1095 non-null   str
 5   player_of_match  1090 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1090 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  method           21 non-null     str
 18  umpire1          1095 non-null   str
 19  umpire2          1095 non-null   str
dtypes: float64(3), int64(1), str(16)
memory usage: 171.2 KB
<class 'pandas.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  str
 3   bowling_team      260920 non-null  str
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  str
 7   bowler            260920 non-null  str
 8   non_striker       260920 non-null  str
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   str
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   str
 15  dismissal_kind    12950 non-null   str
 16  fielder           9354 non-null    str
dtypes: int64(8), str(9)
memory usage: 33.8 MB

In [8]:
matches.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [9]:
deliveries.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [12]:
matches['winner'] = matches['winner'].fillna('No Result')
matches['player_of_match'] = matches['player_of_match'].fillna('Unknown')

In [13]:
matches.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       0
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                0
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [14]:
matches['date'] = pd.to_datetime(matches['date'])

In [15]:
matches.drop_duplicates(inplace=True)
deliveries.drop_duplicates(inplace=True)

In [16]:
matches['city'] = matches['city'].fillna('Unknown')
matches['result_margin'] = matches['result_margin'].fillna('No Result')

In [17]:
matches.isnull().sum()

id                    0
season                0
city                  0
date                  0
match_type            0
player_of_match       0
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                0
result                0
result_margin         0
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [18]:
deliveries['player_dismissed'] = deliveries['player_dismissed'].fillna('Not Out')

In [19]:
deliveries['extras_type'] = deliveries['extras_type'].fillna('None')
deliveries['dismissal_kind'] = deliveries['dismissal_kind'].fillna('None')

In [20]:
deliveries.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type              0
is_wicket                0
player_dismissed         0
dismissal_kind           0
fielder             251566
dtype: int64

In [21]:
deliveries['fielder'] = deliveries['fielder'].fillna('No Fielder')

In [22]:
deliveries.isnull().sum()

match_id            0
inning              0
batting_team        0
bowling_team        0
over                0
ball                0
batter              0
bowler              0
non_striker         0
batsman_runs        0
extra_runs          0
total_runs          0
extras_type         0
is_wicket           0
player_dismissed    0
dismissal_kind      0
fielder             0
dtype: int64

In [23]:
matches['method'] = matches['method'].fillna('Normal Match')

In [24]:
matches.isnull().sum()

id                 0
season             0
city               0
date               0
match_type         0
player_of_match    0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             0
result             0
result_margin      0
target_runs        3
target_overs       3
super_over         0
method             0
umpire1            0
umpire2            0
dtype: int64

In [25]:
matches['target_overs'] = matches['target_overs'].fillna(0)

In [26]:
matches.isnull().sum()

id                 0
season             0
city               0
date               0
match_type         0
player_of_match    0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             0
result             0
result_margin      0
target_runs        3
target_overs       0
super_over         0
method             0
umpire1            0
umpire2            0
dtype: int64

In [27]:
matches['target_runs'] = matches['target_runs'].fillna(0)

In [28]:
matches.isnull().sum()

id                 0
season             0
city               0
date               0
match_type         0
player_of_match    0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             0
result             0
result_margin      0
target_runs        0
target_overs       0
super_over         0
method             0
umpire1            0
umpire2            0
dtype: int64

In [31]:
matches['win_type'] = matches['result'].apply(
    lambda x: 'Defend' if x == 'runs' else ('Chase' if x == 'wickets' else 'No Result')
)

In [32]:
matches[['result', 'win_type']].head(5)

    result win_type
0     runs   Defend
1     runs   Defend
2  wickets    Chase
3  wickets    Chase
4  wickets    Chase

In [33]:
matches['year'] = matches['date'].dt.year

In [34]:
matches['toss_win_match_win'] = (
    matches['toss_winner'] == matches['winner']
)

In [35]:
matches['toss_win_match_win'].head(5)

0    False
1     True
2    False
3    False
4    False
Name: toss_win_match_win, dtype: bool

In [36]:
total_runs = deliveries.groupby('match_id')['total_runs'].sum().reset_index()
wickets = deliveries[deliveries['is_wicket'] == 1] \
    .groupby('match_id').size().reset_index(name='total_wickets')

In [37]:
df = matches.merge(total_runs, left_on='id', right_on='match_id')
df = df.merge(wickets, left_on='id', right_on='match_id')

In [40]:
df.tail(5)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,method,umpire1,umpire2,win_type,year,toss_win_match_win,match_id_x,total_runs,match_id_y,total_wickets
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,...,Normal Match,Nitin Menon,VK Sharma,Chase,2024,False,1426307,429,1426307,11
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,Normal Match,AK Chaudhary,R Pandit,Chase,2024,False,1426309,323,1426309,12
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,...,Normal Match,KN Ananthapadmanabhan,MV Saidharshan Kumar,Chase,2024,True,1426310,346,1426310,14
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,...,Normal Match,Nitin Menon,VK Sharma,Defend,2024,False,1426311,314,1426311,16
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,Normal Match,J Madanagopal,Nitin Menon,Chase,2024,False,1426312,227,1426312,12

In [41]:
df.drop(columns=['match_id_x', 'match_id_y'], inplace=True)

In [42]:
df.head(5)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,target_overs,super_over,method,umpire1,umpire2,win_type,year,toss_win_match_win,total_runs,total_wickets
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,20.0,N,Normal Match,Asad Rauf,RE Koertzen,Defend,2008,False,304,13
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,20.0,N,Normal Match,MR Benson,SL Shastri,Defend,2008,True,447,9
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,20.0,N,Normal Match,Aleem Dar,GA Pratapkumar,Chase,2008,False,261,9
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,20.0,N,Normal Match,SJ Davis,DJ Harper,Chase,2008,False,331,12
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,20.0,N,Normal Match,BF Bowden,K Hariharan,Chase,2008,False,222,15

In [45]:
runs_innings = deliveries.groupby(['match_id', 'inning'])['total_runs'].sum().reset_index()
runs_pivot = runs_innings.pivot(index='match_id',  columns='inning',  values='total_runs').reset_index()
runs_pivot = runs_pivot.rename(columns={ 1: 'runs_1st_innings', 2: 'runs_2nd_innings'})
runs_pivot[['runs_1st_innings', 'runs_2nd_innings']] = runs_pivot[['runs_1st_innings', 'runs_2nd_innings']].fillna(0)

In [47]:
wickets_innings = deliveries[deliveries['is_wicket'] == 1].groupby(['match_id', 'inning']).size().reset_index(name='wickets')
wickets_pivot = wickets_innings.pivot( index='match_id', columns='inning', values='wickets').reset_index()
wickets_pivot = wickets_pivot.rename(columns={ 1: 'wickets_1st_inning', 2: 'wickets_2nd_inning'})  
wickets_pivot[['wickets_1st_inning', 'wickets_2nd_inning']] = wickets_pivot[['wickets_1st_inning', 'wickets_2nd_inning']].fillna(0)

In [48]:
df = df.merge(runs_pivot, left_on='id', right_on='match_id')
df = df.merge(wickets_pivot, left_on='id', right_on='match_id')

In [49]:
df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,3_x,4_x,5_x,6,match_id_y,wickets_1st_inning,wickets_2nd_inning,3_y,4_y,5_y
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,NaN,NaN,NaN,NaN,335982,3.0,10.0,NaN,NaN,NaN
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,NaN,NaN,NaN,NaN,335983,5.0,4.0,NaN,NaN,NaN
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,NaN,NaN,NaN,NaN,335984,8.0,1.0,NaN,NaN,NaN
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,NaN,NaN,NaN,NaN,335985,7.0,5.0,NaN,NaN,NaN
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,NaN,NaN,NaN,NaN,335986,10.0,5.0,NaN,NaN,NaN

In [50]:
df.drop(columns=['match_id_x', 'match_id_y'], inplace=True, errors='ignore')

In [51]:
df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,runs_2nd_innings,3_x,4_x,5_x,6,wickets_1st_inning,wickets_2nd_inning,3_y,4_y,5_y
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,82.0,NaN,NaN,NaN,NaN,3.0,10.0,NaN,NaN,NaN
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,207.0,NaN,NaN,NaN,NaN,5.0,4.0,NaN,NaN,NaN
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,132.0,NaN,NaN,NaN,NaN,8.0,1.0,NaN,NaN,NaN
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,166.0,NaN,NaN,NaN,NaN,7.0,5.0,NaN,NaN,NaN
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,112.0,NaN,NaN,NaN,NaN,10.0,5.0,NaN,NaN,NaN

In [54]:
runs_pivot = runs_pivot.rename(columns={1: 'runs_1st_innings', 2: 'runs_2nd_innings'})

for col in ['runs_1st_innings', 'runs_2nd_innings']:
    if col not in runs_pivot.columns:
        runs_pivot[col] = 0

runs_pivot[['runs_1st_innings', 'runs_2nd_innings']] = runs_pivot[['runs_1st_innings', 'runs_2nd_innings']].fillna(0)

In [55]:
df.head(5)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,runs_2nd_innings,3_x,4_x,5_x,6,wickets_1st_inning,wickets_2nd_inning,3_y,4_y,5_y
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,82.0,NaN,NaN,NaN,NaN,3.0,10.0,NaN,NaN,NaN
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,207.0,NaN,NaN,NaN,NaN,5.0,4.0,NaN,NaN,NaN
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,132.0,NaN,NaN,NaN,NaN,8.0,1.0,NaN,NaN,NaN
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,166.0,NaN,NaN,NaN,NaN,7.0,5.0,NaN,NaN,NaN
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,112.0,NaN,NaN,NaN,NaN,10.0,5.0,NaN,NaN,NaN

In [57]:
df = df.drop(columns=[
    col for col in df.columns 
    if '_x' in str(col) or '_y' in str(col) or col in [3,4,5,6]
], errors='ignore')

In [58]:
df.head(5)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,umpire2,win_type,year,toss_win_match_win,total_runs,total_wickets,runs_1st_innings,runs_2nd_innings,wickets_1st_inning,wickets_2nd_inning
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,RE Koertzen,Defend,2008,False,304,13,222.0,82.0,3.0,10.0
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,SL Shastri,Defend,2008,True,447,9,240.0,207.0,5.0,4.0
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,GA Pratapkumar,Chase,2008,False,261,9,129.0,132.0,8.0,1.0
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,DJ Harper,Chase,2008,False,331,12,165.0,166.0,7.0,5.0
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,K Hariharan,Chase,2008,False,222,15,110.0,112.0,10.0,5.0

In [59]:
df[['runs_1st_innings','runs_2nd_innings','wickets_1st_inning','wickets_2nd_inning']].isnull().sum()

runs_1st_innings      0
runs_2nd_innings      0
wickets_1st_inning    0
wickets_2nd_inning    0
dtype: int64

In [60]:
df[['runs_1st_innings','runs_2nd_innings','wickets_1st_inning','wickets_2nd_inning']] = \
df[['runs_1st_innings','runs_2nd_innings','wickets_1st_inning','wickets_2nd_inning']].astype(int)

In [61]:
df.head(5)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,umpire2,win_type,year,toss_win_match_win,total_runs,total_wickets,runs_1st_innings,runs_2nd_innings,wickets_1st_inning,wickets_2nd_inning
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,RE Koertzen,Defend,2008,False,304,13,222,82,3,10
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,SL Shastri,Defend,2008,True,447,9,240,207,5,4
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,GA Pratapkumar,Chase,2008,False,261,9,129,132,8,1
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,DJ Harper,Chase,2008,False,331,12,165,166,7,5
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,K Hariharan,Chase,2008,False,222,15,110,112,10,5

In [62]:
matches['winner'].value_counts().head(10)

winner
Mumbai Indians                 144
Chennai Super Kings            138
Kolkata Knight Riders          131
Royal Challengers Bangalore    116
Rajasthan Royals               112
Kings XI Punjab                 88
Sunrisers Hyderabad             88
Delhi Daredevils                67
Delhi Capitals                  48
Deccan Chargers                 29
Name: count, dtype: int64

In [63]:
toss_win_match = (df['toss_winner'] == df['winner']).mean() * 100
toss_win_match

np.float64(50.593607305936075)

In [64]:
df['batting_first'] = df['toss_decision'].apply(lambda x: 1 if x == 'bat' else 0)
df.groupby('batting_first')['winner'].count()

batting_first
0    704
1    391
Name: winner, dtype: int64

In [65]:
df['winner'].value_counts()

winner
Mumbai Indians                 144
Chennai Super Kings            138
Kolkata Knight Riders          131
Royal Challengers Bangalore    116
Rajasthan Royals               112
Kings XI Punjab                 88
Sunrisers Hyderabad             88
Delhi Daredevils                67
Delhi Capitals                  48
Deccan Chargers                 29
Gujarat Titans                  28
Punjab Kings                    24
Lucknow Super Giants            24
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Royal Challengers Bengaluru      7
Kochi Tuskers Kerala             6
No Result                        5
Rising Pune Supergiants          5
Name: count, dtype: int64

In [66]:
df[['runs_1st_innings','runs_2nd_innings']].mean()

runs_1st_innings    165.547032
runs_2nd_innings    151.777169
dtype: float64

In [67]:
df[df['runs_1st_innings'] - df['runs_2nd_innings'] <= 10]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,win_type,year,toss_win_match_win,total_runs,total_wickets,runs_1st_innings,runs_2nd_innings,wickets_1st_inning,wickets_2nd_inning,batting_first
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,Chase,2008,False,261,9,129,132,8,1,1
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,Chase,2008,False,331,12,165,166,7,5,1
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,Chase,2008,False,222,15,110,112,10,5,1
5,335987,2007/08,Jaipur,2008-04-21,League,SR Watson,Sawai Mansingh Stadium,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,...,Chase,2008,False,334,12,166,168,8,4,1
6,335988,2007/08,Hyderabad,2008-04-22,League,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Delhi Daredevils,Deccan Chargers,...,Chase,2008,False,285,9,142,143,8,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1087,1426303,2024,Guwahati,2024-05-15,League,SM Curran,"Barsapara Cricket Stadium, Guwahati",Rajasthan Royals,Punjab Kings,Rajasthan Royals,...,Chase,2024,False,289,14,144,145,9,5,1
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,...,Chase,2024,False,429,11,214,215,5,6,1
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,Chase,2024,False,323,12,159,164,10,2,1
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,...,Chase,2024,True,346,14,172,174,8,6,0
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,Chase,2024,False,227,12,113,114,10,2,1

In [68]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [69]:
df.to_csv('ipl_cleaned_data.csv',index=False)

In [70]:
from sqlalchemy import create_engine

In [71]:
df=pd.read_csv('ipl_cleaned_data.csv')

In [72]:
df

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,win_type,year,toss_win_match_win,total_runs,total_wickets,runs_1st_innings,runs_2nd_innings,wickets_1st_inning,wickets_2nd_inning,batting_first
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,Defend,2008,False,304,13,222,82,3,10,0
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,Defend,2008,True,447,9,240,207,5,4,1
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,Chase,2008,False,261,9,129,132,8,1,1
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,Chase,2008,False,331,12,165,166,7,5,1
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,Chase,2008,False,222,15,110,112,10,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,...,Chase,2024,False,429,11,214,215,5,6,1
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,Chase,2024,False,323,12,159,164,10,2,1
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,...,Chase,2024,True,346,14,172,174,8,6,0
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,...,Defend,2024,False,314,16,175,139,9,7,0
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,Chase,2024,False,227,12,113,114,10,2,1

In [73]:
engine = create_engine("mysql+pymysql://root:password@localhost:3306/ipl_analysis_db")

In [74]:
df.to_sql('ipl_matches_summary', con=engine, if_exists='replace', index=False)

1095